import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import TopCards from "../components/TopCards";
import Activity from "../components/Activity";
import Graph from "../components/Graph";


export default function Home() {
  return (
    <>
      <Head>
        <title>digital nao</title>
        <meta name="description" content="generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <main className='bg-base-200 min-h-screen'>
          <Header />
          <TopCards />
          <div className='p-4 grid md:grid-cols-2 grid-cols-1 gap-4'>
          <Activity />
          <Graph/>
          </div>
        </main>
    </>
  );
}